In [1]:
# NumPy for AI - Mini Project Assignment

import numpy as np

# STEP 1: Create Dataset of 10 Students
# Columns:

data = np.array([
    [78, 85, 80, 90, 1],
    [45, 50, 40, 55, 0],
    [88, 92, 84, 91, 1],
    [60, 65, 58, 62, 1],
    [35, 40, 30, 45, 0],
    [95, 90, 93, 97, 1],
    [55, 48, 52, 50, 0],
    [72, 70, 75, 78, 1],
    [40, 42, 38, 35, 0],
    [82, 79, 85, 88, 1]
])

print("Dataset:")
print(data)

# STEP 2: Separate Features (X) and Labels (y)
X = data[:, 0:4]
y = data[:, 4]

print("Features (X):")
print(X)

print("Labels (y):")
print(y)

# STEP 3: Calculate Average, Maximum, Minimum Marks

average_marks = np.mean(X, axis=0)
maximum_marks = np.max(X, axis=0)
minimum_marks = np.min(X, axis=0)

subjects = ["Math", "Science", "English", "Computer"]

print("Average Marks:")
for i in range(4):
    print(subjects[i], "=", average_marks[i])

print("Maximum Marks:")
for i in range(4):
    print(subjects[i], "=", maximum_marks[i])

print("Minimum Marks:")
for i in range(4):
    print(subjects[i], "=", minimum_marks[i])

# STEP 4: Count Passed and Failed Students

passed_students = np.sum(y == 1)
failed_students = np.sum(y == 0)

print("Number of Passed Students =", passed_students)
print("Number of Failed Students =", failed_students)

# STEP 5: Students Scoring Above 80 and Below 50
above_80 = X[X > 80]
below_50 = X[X < 50]

print("Marks Above 80:")
print(above_80)

print("Marks Below 50:")
print(below_50)
# STEP 6: Normalize Dataset
# Formula:
# x_norm = (x - min) / (max - min)


X_norm = (X - np.min(X)) / (np.max(X) - np.min(X))

print("Normalized Dataset:")
print(X_norm)

# STEP 7: Simple Prediction Logic
# If average marks >= 60 → Pass (1)
# Else → Fail (0)


average_student_marks = np.mean(X, axis=1)

predictions = np.where(average_student_marks >= 60, 1, 0)

print("Predicted Results:")
print(predictions)

# STEP 8: Calculate Accuracy
accuracy = np.mean(predictions == y) * 100

print("Actual Results:")
print(y)

print("Accuracy =", accuracy, "%")

Dataset:
[[78 85 80 90  1]
 [45 50 40 55  0]
 [88 92 84 91  1]
 [60 65 58 62  1]
 [35 40 30 45  0]
 [95 90 93 97  1]
 [55 48 52 50  0]
 [72 70 75 78  1]
 [40 42 38 35  0]
 [82 79 85 88  1]]
Features (X):
[[78 85 80 90]
 [45 50 40 55]
 [88 92 84 91]
 [60 65 58 62]
 [35 40 30 45]
 [95 90 93 97]
 [55 48 52 50]
 [72 70 75 78]
 [40 42 38 35]
 [82 79 85 88]]
Labels (y):
[1 0 1 1 0 1 0 1 0 1]
Average Marks:
Math = 65.0
Science = 66.1
English = 63.5
Computer = 69.1
Maximum Marks:
Math = 95
Science = 92
English = 93
Computer = 97
Minimum Marks:
Math = 35
Science = 40
English = 30
Computer = 35
Number of Passed Students = 6
Number of Failed Students = 4
Marks Above 80:
[85 90 88 92 84 91 95 90 93 97 82 85 88]
Marks Below 50:
[45 40 35 40 30 45 48 40 42 38 35]
Normalized Dataset:
[[0.71641791 0.82089552 0.74626866 0.89552239]
 [0.2238806  0.29850746 0.14925373 0.37313433]
 [0.86567164 0.92537313 0.80597015 0.91044776]
 [0.44776119 0.52238806 0.41791045 0.47761194]
 [0.07462687 0.14925373 0.      