In [2]:
import numpy as np

# 1D Array
arr1 = np.arange(1,11)

# 2D Array
arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

zeros_arr = np.zeros((4,4))

ones_arr = np.ones((2,5))
print(arr1)
print(arr2)
print(zeros_arr)
print(ones_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)
print(arr2.ndim)

(3, 3)
9
int64
2


In [4]:
arr = np.array([10,20,30,40,50,60])

print(arr[0])
print(arr[-1])
print(arr[2])

print(arr[arr > 30])

10
60
30
[40 50 60]


In [5]:
print(arr[1:5])

print(arr[::-1])

print(arr[::2])

mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

print(mat[0])

print(mat[:,1])

print(mat[1:])

[20 30 40 50]
[60 50 40 30 20 10]
[10 30 50]
[1 2 3]
[2 5 8]
[[4 5 6]
 [7 8 9]]


In [6]:
arr = np.array([1,2,3,4,5])

print(arr * 5)

print(arr + 10)

print(arr ** 2)

[ 5 10 15 20 25]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [7]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr + 10)

print(arr * 2)

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]


In [8]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(A + B)

print(A - B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [9]:
A = np.array([[1,2],
              [3,4]])

B = np.array([[5,6],
              [7,8]])

print(np.dot(A,B))

print(A.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [10]:
 rand_int = np.random.randint(1,101,(4,4))

rand_float = np.random.rand(4,4)

print(rand_int)

print(rand_int.max())

print(rand_int.min())

print(rand_int.mean())

[[36  9 63 54]
 [ 9 56 97 57]
 [33 38 78 54]
 [27  3  7  3]]
97
3
39.0


In [11]:
marks = np.array([45,78,88,92,67,54,81,73,49,90])

print(marks.mean())

print(marks.max())

print(marks.min())

print(np.sum(marks > 80))

print(marks[marks < 50])

71.7
92
45
4
[45 49]


In [12]:
img = np.random.randint(0,256,(5,5))

print(img)

print(img.max())

print(img.min())

print(img.shape)

[[150 150  50  63  19]
 [130 195 122 111  62]
 [ 83 208  65 110  32]
 [ 30  40 115 209  24]
 [ 75 132  34 234   7]]
234
7
(5, 5)


In [13]:
data = np.array([10,20,30,40,50])

normalized = (data - data.min()) / (data.max() - data.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [14]:
data = np.array([
    [25,30000,0],
    [30,50000,1],
    [35,60000,1],
    [28,35000,0]
])

X = data[:,:2]

y = data[:,2]

print(X)

print(y)

print(X[:,1].mean())

print(X[:,0].max())

print(data.shape)

[[   25 30000]
 [   30 50000]
 [   35 60000]
 [   28 35000]]
[0 1 1 0]
43750.0
35
(4, 3)
